# Generated by Django 3.1.7 on 2021-03-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homePage', '0002_delete_slideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandList',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
            ],
        ),
    ]
