# Generated by Django 3.1.7 on 2021-03-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_brandlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='scentNotes',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=200)),
            ],
        ),
    ]
