# Generated by Django 3.1.7 on 2021-03-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_scentnotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scentNotes',
            new_name='scentNote',
        ),
    ]
