# Generated by Django 3.2 on 2021-05-17 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_auto_20210329_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.brandlist')),
            ],
        ),
    ]
