# Generated by Django 3.2 on 2021-05-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='sname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
