# Generated by Django 3.2 on 2021-05-20 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homePage', '0008_auto_20210519_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='longevity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='perfume',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='perfume',
            name='ratecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='scentnote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homePage.scentnote'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='sillage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='perfume',
            name='yearofreleasing',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfumepoint', models.IntegerField(default=0)),
                ('longevity', models.IntegerField(default=0)),
                ('sillage', models.IntegerField(default=0)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
