# Generated by Django 3.2 on 2021-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_auto_20210520_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='content',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='ratecount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='yearofreleasing',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='longevity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='perfumepoint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sillage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
