# Generated by Django 3.2 on 2021-05-23 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_auto_20210520_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='longevity',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='point',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='ratecount',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='sillage',
        ),
        migrations.AlterField(
            model_name='rate',
            name='longevity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='homePage.perfume'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='perfumepoint',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sillage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
