# Generated by Django 3.2 on 2021-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0011_auto_20210523_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='sex',
            field=models.CharField(choices=[('male', 'Nam'), ('nu', 'Nữ'), ('unisex', 'Unisex')], default='unisex', max_length=6),
        ),
    ]
