# Generated by Django 3.2 on 2021-05-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0014_rename_perfume_rate_perfume_rated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='perfume_rated',
            new_name='perfume',
        ),
    ]
