# Generated by Django 3.1.7 on 2021-12-20 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homePage', '0017_ratevote'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Finished', max_length=200)),
                ('totalPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('user', 'perfume'), name='rate_once'),
        ),
        migrations.AddConstraint(
            model_name='ratevote',
            constraint=models.UniqueConstraint(fields=('user', 'rate'), name='vote_rate_once'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='homePage.order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.perfume'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='homePage.perfume'),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
