# Generated by Django 3.1.7 on 2021-12-22 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0018_auto_20211220_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandlist',
            name='image',
            field=models.FileField(blank=True, upload_to='brand-image', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, upload_to='perfume-pic'),
        ),
        migrations.AddField(
            model_name='scentnote',
            name='image',
            field=models.ImageField(blank=True, upload_to='scent-image'),
        ),
    ]
