# Generated by Django 3.1.7 on 2021-12-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0019_auto_20211222_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
